## Introduction: Bias-Variance Tradeoff

Increasing the complexity of a model in search for better performance leads to a Bias-Variance Tradeoff.

- Bias is the error due to wrong assumptions. A high bias model is most likely to underfit the training data.

- Variance is the amount that the estimate of the target function will change if different training data were used. A model with many degrees of freedom (such as a high-degree polynomial) is likely to have high variance and underfit the data.

In short: a model with high bias will *underfit* the data, while a model with high variance will *overfit* the data.

The goal is to find the sweet spot where the model is complex enough to capture the underlying patterns in the data, but not so complex that it starts capturing noise.

- Overfitting: the model will perform well on the training set but poorly on the test set.
- Underfitting: the model has high bias, it will perform poorly on both the training set and the test set.

## Regularization

Constraining a model to make it simpler and reduce the risk of overfitting is called regularization.

The amount of regularization applied is controlled by what is called a hyperparameter.

A hyperparameter is a parameter of a learning algorithm and not of the model, as such it is not affected by the learning algorithm itself; it must be set prior to training and remains constant during training.

If you set the regularization hyperparameter to a very large value, you will get an almost flat model (a slope close to zero); the learning algorithm will almost certainly not overfit the training data, but it will be less likely to find a good solution.

Regularization seeks to solve the overfitting problem by:

- Minimizing the model complexity
- Penalizing the loss function
- Adding more bias to reduce variance

There are three types of regularization.

#### **L1 regularization** (Lasso regression)

Adds a penalty equal to the absolute value of the magnitude of the coefficients.
- it limits the size of the coefficients
- it can yield sparse models where some coefficients can become zero zero

The absolute value of a number is the number without its sign. For example, the absolute value of -3 is 3. The *magnitude* is the length of a vector in a vector space.

Where:
- $\lambda$ is the hyperparameter
- $w$ are the coefficients (weight) of the model
- $n$ is the number of features

$$Loss = MSE + \lambda \sum_{i=1}^{n} |w_i|$$

#### **L2 regularization** (Ridge regression)

Adds a penalty equal to the square of the magnitude of the coefficients.

- All coefficients are shrunk by the same factor (none are eliminated)
- Does not necessarily eliminate coefficients

$$Loss = MSE + \lambda \sum_{i=1}^{n} w_i^2$$

#### **Elastic Net**

Elastic Net is a combination of L1 and L2 regularization. It adds both penalties to the loss function.

- It works well when there are multiple features correlated with each other
- It can be used to select important features
- It can be used to handle multicollinearity

$$\text{Loss} = \text{MSE} + \lambda \left( \alpha \sum_{i=1}^n |w_i| + \frac{1 - \alpha}{2} \sum_{i=1}^n w_i^2 \right)$$

## Feature Scaling

Feature scaling is a method used to normalize the range of independent variables or features of data. In data processing, it is also known as data normalization and is generally performed during the data preprocessing step.

The goal of normalization is to change the values of numeric columns in the dataset to a common scale, without distorting differences in the ranges of values. For machine learning, every dataset does not require normalization. It is required only when features have different ranges.

Feature scaling applies to one column at a time.

The two most popular techniques for feature scaling are normalization and standardization.

### Normalization

Normalization works better when the features are normally distributed.

#### Rescaling (min-max normalization)

Also known as min-max scaling or min-max normalization, rescaling is the simplest method and consists in rescaling the range of features to scale the range in [0, 1] or [−1, 1]

$$x' = \frac{x - x_{min}}{x_{max} - x_{min}}$$

Rescaling can be applied to an arbitrary range [a, b] using the following formula, where $a$ and $b$ are the minimum and maximum values of the desired range:

$$x' = a + \frac{(x - x_{min})(b - a)}{x_{max} - x_{min}}$$

The values of the feature will be between 0 and 1.

#### Mean normalization

$$x' = \frac{x - \bar{x}}{x_{max} - x_{min}}$$

#### Standardization (Z-score normalization)

Data can include multiple dimensions. Feature standardization makes the values of each feature in the data have zero-mean (when subtracting the mean in the numerator) and unit-variance. This method is widely used for normalization in many machine learning algorithms (e.g., support vector machines, logistic regression, and artificial neural networks).

$$x' = \frac{x - \bar{x}}{\sigma}$$

All values inside the column will be between -3 and 3, approximately. Outliers can end up outside this range.

#### Robust scaling

Also known as *standardization using median and interquartile range (IQR)*, is designed to be robust to outliers. It scales features using the median and IQR as reference points instead of the mean and standard deviation.

Where $Q_1(x)$ and $Q_3(x)$ are the first and third quartiles of the data, respectively:

$$x' = \frac{x - Q_2(x)}{Q_3(x) - Q_1(x)}$$

#### Examples (data preprocessing)

**Important: the convention with scikit-learn (sklearn) is to capitalize the dependent variable (X)**

In [1]:
import numpy as np
import pandas as pd

##### Example 1

1. Importing the dataset
2. Selecting the columns

In [2]:
dataset = pd.read_csv('./data/preprocessing.csv')
# select all rows, all columns except the last one
X = dataset.iloc[:, :-1].values
# all rows, only the last column
y = dataset.iloc[:, -1].values

In [3]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [4]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

3. Handling missing data

In [5]:
# handling missing numerical data
from sklearn.impute import SimpleImputer
# replace NaN values with the mean of the other values in the same column
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# specify the columns with numerical values
imputer.fit(X[:, 1:3])
# replace the missing data with the parameter values specified in the previous steps
X[:, 1:3] = imputer.transform(X[:, 1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

4. Encoding categorical data: independent variable

   Encoding the independent variable by splitting the column with categorical data into multiple columns, one for each category.

    This process is called one-hot encoding: for each category, a binary vector is created.

    In this example, the first column is split into three columns: France, Spain, and Germany.

    France vector: [1, 0, 0], Spain vector: [0, 1, 0], Germany vector: [0, 0, 1]

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# specify the encoding method, the column to encode, and what to do with the other columns
# in this case, the other columns are left untouched (remainder='passthrough')
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# transform the data in a numpy array, then apply the encoding
X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

5. Encoding categorical data: dependent variable (the target label)

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

6. Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split
# the test set will contain 20% of the data, random_state is set to 1 for learning purposes
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [9]:
X_train

array([[0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [10]:
X_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [11]:
y_train

array([0, 1, 0, 0, 1, 1, 0, 1])

In [12]:
y_test

array([0, 1])

7. Feature Scaling

Note: the dummy variables (created by one-hot encoding) should **not** be scaled.

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
X_train

array([[-0.77459667, -0.57735027,  1.29099445, -0.19159184, -1.07812594],
       [-0.77459667,  1.73205081, -0.77459667, -0.01411729, -0.07013168],
       [ 1.29099445, -0.57735027, -0.77459667,  0.56670851,  0.63356243],
       [-0.77459667, -0.57735027,  1.29099445, -0.30453019, -0.30786617],
       [-0.77459667, -0.57735027,  1.29099445, -1.90180114, -1.42046362],
       [ 1.29099445, -0.57735027, -0.77459667,  1.14753431,  1.23265336],
       [-0.77459667,  1.73205081, -0.77459667,  1.43794721,  1.57499104],
       [ 1.29099445, -0.57735027, -0.77459667, -0.74014954, -0.56461943]])

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
# fit the scaler to the training set and transform it
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
# transform the test set but do not fit
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [16]:
X_train

array([[-0.77459667, -0.57735027,  1.29099445, -0.19159184, -1.07812594],
       [-0.77459667,  1.73205081, -0.77459667, -0.01411729, -0.07013168],
       [ 1.29099445, -0.57735027, -0.77459667,  0.56670851,  0.63356243],
       [-0.77459667, -0.57735027,  1.29099445, -0.30453019, -0.30786617],
       [-0.77459667, -0.57735027,  1.29099445, -1.90180114, -1.42046362],
       [ 1.29099445, -0.57735027, -0.77459667,  1.14753431,  1.23265336],
       [-0.77459667,  1.73205081, -0.77459667,  1.43794721,  1.57499104],
       [ 1.29099445, -0.57735027, -0.77459667, -0.74014954, -0.56461943]])

In [17]:
X_test

array([[-0.77459667,  1.73205081, -0.77459667, -1.46618179, -0.9069571 ],
       [ 1.29099445, -0.57735027, -0.77459667, -0.44973664,  0.20564034]])